/*
 * HTMLHelp.java
 *
 * Created on 19. Januar 2006, 17:54
 */

package logicsim;

import javax.swing.*;
import java.awt.AWTEvent;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.Objects;

/**
 *
 * @author atetzl
 */
public class HTMLHelp extends javax.swing.JFrame implements java.awt.event.ActionListener {
	private static final long serialVersionUID = 4292051858178374722L;
	private JButton jButton_ok;
	private JScrollPane jScrollPane1;
	private JTextPane jTextPane1;

	Toolkit toolkit = Toolkit.getDefaultToolkit();

	/** Creates new form HTMLHelp */
	public HTMLHelp() {
		String language = LSProperties.getInstance().getProperty("language", "de");
		Dimension scrSize;
		int width = 800, height = 600;

		getContentPane().setLayout(new BorderLayout(0, 0));
		initComponents();
		this.enableEvents(AWTEvent.MOUSE_EVENT_MASK);

		scrSize = toolkit.getScreenSize();
		setLocation((scrSize.width / 2) - (width / 2), (scrSize.height / 2) - (height / 2));
		setSize(width, height);
		this.setTitle("LogicSim " + I18N.tr(Lang.HELP));

		try {
			String resourcePath = "/docs/" + language + ".html";
			java.net.URL url = getClass().getResource(resourcePath);
			if (url == null) {
				url = getClass().getResource("/docs/en.html");
			}
			if (url != null) {
				jTextPane1.setPage(url);
			} else {
				throw new java.io.FileNotFoundException("Docs file not found: " + resourcePath);
			}
		} catch (Exception ex) {
			ex.printStackTrace();
			this.setVisible(false);
			this.dispose();
		}
		this.setVisible(true);
	}

	protected void processMouseEvent(MouseEvent e) {
		super.processMouseEvent(e);
		int id = e.getID();
		if (id == MouseEvent.MOUSE_CLICKED) {
			this.setVisible(false);
			this.dispose();
		}
	}

	protected void processWindowEvent(WindowEvent e) {
		// super.processWindowEvent(e);
		if (e.getID() == WindowEvent.WINDOW_CLOSING) {
			this.dispose();
		}
	}

	public void actionPerformed(ActionEvent e) {
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	private void initComponents() {
		jButton_ok = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextPane1 = new javax.swing.JTextPane();
		jTextPane1.setContentType("text/html;charset=UTF-8");
		
		jButton_ok.setText("OK");
		jButton_ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_okActionPerformed(evt);
			}
		});

		getContentPane().add(jButton_ok, java.awt.BorderLayout.SOUTH);

		jTextPane1.setEditable(false);
		jTextPane1.setMinimumSize(new java.awt.Dimension(400, 300));
		jScrollPane1.setViewportView(jTextPane1);

		getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

		pack();
	}

	private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_okActionPerformed
		this.dispose();
		this.setVisible(false);
	}

}
