# Main menu entries
menu.file=Datei
menu.file.new=Neu
menu.file.open=\u00D6ffnen
menu.file.save=Speichern
menu.file.saveas=Speichern Als
menu.file.properties=Eigenschaften
menu.file.export=Export
menu.file.exit=Exit
menu.module=Modul
menu.module.create=Modul erstellen
menu.module.load=Modul laden
menu.settings=Einstellungen
menu.settings.paintgrid=Raster zeichnen
menu.settings.autowire=Autom. Verkabelung
menu.settings.gatedesign=Gatterdesign
menu.settings.gatedesign.iec=IEC
menu.settings.gatedesign.ansi=ANSI
menu.settings.complexity=Komplexit\u00E4t
menu.settings.complexity.level0=Anf\u00E4nger
menu.settings.complexity.level1=Level 2
menu.settings.complexity.level2=Normal
menu.settings.complexity.level3=Level 4
menu.settings.complexity.level4=Erweitert
menu.settings.colormode=Farbmodus
menu.settings.colormode.on=An
menu.settings.colormode.off=Aus
menu.settings.language=Sprache
menu.help=Hilfe
menu.help.help=Hilfe
menu.help.about=\u00DCber LogicSim

# Popup menu on right-click
popup.removegate=Gatter l\u00F6schen
popup.properties=Eigenschaften
popup.disconnect=Gatter entkoppeln
popup.rotate=Rotieren
popup.addinput=Eingang hinzuf\u00FCgen
popup.removeinput=Eingang entfernen

# Other main window entries
mainpanel.combo.inputs=Eing\u00E4nge

# Tooltips shown when hovering over toolbar buttons
toolbar.new=Neu
toolbar.open=\u00D6ffnen
toolbar.save=Speichern
toolbar.simulate=Simulieren
toolbar.inputnormal=Normaler Eingang
toolbar.inputinv=Invertierter Eingang
toolbar.inputhigh=High Eingang
toolbar.inputlow=Low Eingang
toolbar.wirenew=Neues Kabel
toolbar.addpoint=Punkt zu Kabel hinzuf\u00FCgen
toolbar.removepoint=Punkt von Kabel entfernen
toolbar.zoomin=Hereinzoomen
toolbar.zoomout=Herauszoomen

# Status bar messages
status.inputnormal.help=Klicke auf einen Input, um ihn auf NORMAL zu setzen
status.inputinv.help=Klicke auf einen Input, um ihn zu invertieren
status.inputhigh.help=Klicke auf einen Input, um ihn auf HIGH zu setzen
status.inputlow.help=Klicke auf einen Input, um ihn auf LOW zu setzen
status.addpoint.help=Klicke auf ein Kabel um einen Punkt hinzuzuf\u00FCgen
status.removepoint.help=Klicke auf ein Kabel um einen Punkt zu entfernen
status.wirenew.help=Klicke auf ein Pin, Kabel, Punkt oder freie Stelle um ein Kabel einzuf\u00FCgen
status.gateadded=Gatter hinzugef\u00FCgt
status.saved=Schaltplandatei gespeichert unter %s
status.aborted=abgebrochen
status.simulation.started=Simulation gestarted
status.simulation.stopped=Simulation gestoppt
status.pin=Anschlusspin
status.wire=Kabel
status.wirepoint=Punkt
status.wireedit=Kabel bearbeiten: ESC zum L\u00F6schen des letzten Punkts, DEL zum L\u00F6schen des Kabels, Klick auf Pin zum Beenden
status.onepartdeleted=1 Teil gel\u00F6scht
status.partsdeleted=%s Teile gel\u00F6scht
status.partsselected=%s Teile ausgew\u00E4hlt
status.module=Modul

# Categories in component list
category.basic=Grundgatter
category.inputs=Eingabe
category.outputs=Ausgabe
category.cpu=CPU
category.flipflops=Flip-Flops
category.modules=Module

# Texts shown in dialogs
dialog.fileinfo.label=Beschriftung
dialog.fileinfo.name=Name
dialog.fileinfo.description=Beschreibung
dialog.properties.text=Text
filename.unnamed=Unbenannt
dialog.savecircuit.title=Schaltplandatei speichern
dialog.gateproperties.title=Gatter Eigenschaften
file.type.filter=LogicSim Dateien

# Questions, confirmations and errors
question.confirmdiscard=Der Schaltplan wurde ver\u00E4ndert.\nM\u00F6chtest Du die \u00C4nderungen wirklich verwerfen?
question.confirmsave=Speichern vor dem Schlie\u00DFen?
question.confirmdelete=Wirklich %s l\u00F6schen?
info.needtorestart=LogicSim muss neu gestartet werden
info.needtorestart.title=Sprache ge\u00E4ndert
error.alreadymodule=Der Schaltkreis ist bereits ein Modul. Abbruch!
error.modulenotfound=Kann das Modul %s nicht finden. Bitte kopiere die Moduldatei in das modules-Unterverzeichnis.
error.nomodule=Die Schaltplandatei ist kein Modul
error.readerror=Fehler beim Laden der Datei (falsche LogicSim-Version?)
error.saveerror=Fehler beim Speichern
error.title=Fehler

# Buttons
button.ok=OK
button.cancel=Abbruch
button.yes=Ja
button.no=Nein
button.dontsave=Nicht Speichern

# Gates
gate.and.title=AND
gate.and.description=AND Gatter mit einstellbarer Eingangsanzahl
gate.buffer.title=Puffer
gate.buffer.description=Puffer Gatter
gate.not.title=NOT
gate.not.description=NOT Gatter (Inverter/Negator)
gate.equ.title=EQUIV
gate.equ.description=\u00C4quivalenz Gatter (einstellbare Eingangsanzahl)
gate.nand.title=NAND
gate.nand.description=NAND Gatter mit einstellbarer Eingangsanzahl
gate.nor.title=NOR
gate.nor.description=NOR Gatter mit einstellbarer Eingangsanzahl
gate.or.title=OR
gate.or.description=OR Gatter (einstellbare Eingangsanzahl)
gate.xor.title=XOR
gate.xor.description=XOR Gatter (Antivalenz, einstellbare Eingangsanzahl)
gate.binin.title=Bin\u00E4reingabe
gate.binin.description=Bin\u00E4reingabe (Hex und Bin\u00E4r)
gate.binin.dec=Dezimal (00..255)
gate.binin.hex=Hexadezimal (00..FF)
gate.binin.type=Typ
gate.clock.title=Taktgeber
gate.clock.description=Taktgeber (Clock) mit einstellbaren LOW- und HIGH-Zeiten - Leertaste dr\u00FCcken zum Starten
gate.clock.enterhigh=Dauer High-Pegel (ms)
gate.clock.enterlow=Dauer Low-Pegel (ms)
gate.ondelay.title=Einschaltverz\u00F6gerung
gate.ondelay.description=Verz\u00F6gert das High-Signal
gate.ondelay.delay=Verz\u00F6gerungszeit (ms)
gate.offdelay.title=Ausschaltverz\u00F6gerung
gate.offdelay.description=Verz\u00F6gert das Low-Signal
gate.offdelay.delay=Verz\u00F6gerungszeit (ms)
gate.switch.title=Schalter
gate.switch.description=Schalter (Taster oder Umschalter)
gate.switch.type=Typ
gate.switch.momentary=Taster
gate.switch.toggle=Umschalter
gate.switch4.title=DIP-Schalter (4-fach)
gate.switch4.description=4 Umschalter in einer Einheit - \u00E4hnlich DIP Schalter
gate.switch8.title=Schalter (8-fach)
gate.switch8.description=8 Umschalter in einer Einheit - \u00E4hnlich DIP Schalter
gate.bindisp.title=Bin\u00E4rdisplay
gate.bindisp.description=Bin\u00E4rdisplay (Hex und Bin\u00E4r)
gate.bindisp.type=Typ
gate.bindisp.dec=Dezimal (00..255)
gate.bindisp.hex=Hexadezimal (00..FF)
gate.counter.title=Z\u00E4hler
gate.counter.description=Z\u00E4hlmodul (positive Flanke)
gate.counter.displaytype=Typ
gate.counter.dec=Dezimal (00..255)
gate.counter.hex=Hexadezimal (00..FF)
gate.led.title=LED
gate.led.description=LED
gate.led8.title=Octa LED
gate.led8.description=Acht LEDs in einer Einheit
gate.sevenseg.title=7-Segment Anzeige
gate.sevenseg.description=7 Segment Anzeige zur Darstellung von Ziffern und den Buchstaben a-f
gate.sevendrv.title=7-Segment Treiber
gate.sevendrv.description=Bin\u00E4rzahl-zu-7Segment-Anzeige Konverter
gate.label.title=Textfeld
gate.label.description=Textfeld f\u00FCr Dokumentationszwecke oder Hilfetexte
gate.label.text=Text eingeben
gate.triout.title=Tri-State Output
gate.triout.description=Schaltbarer Ausgang - hochohmig, wenn nicht geschaltet
gate.dff.title=D Flipflop
gate.drff.title=DR Flipflop
gate.drff.description=D Flipflop mit Reset-Eingang
gate.dsrff.title=DSR Flipflop
gate.dsrff.description=D Flipflop mit Setz- und Reset-Eingang
gate.jkff.title=JK Flipflop
gate.jkff.description=Positiv flankengesteuertes JK-Flipflop
gate.monoflop.title=Monoflop
gate.monoflop.hightime=Dauer High-Pegel (ms)
gate.srff.title=SR Flipflop
gate.srrff.title=SRR Flipflop
gate.srl.title=SR Latch
gate.alu8.title=ALU 8bit
gate.alu8.description=8 bit Algorithmic Logic Unit
gate.ctrllogic.title=Control Logic
gate.disp4d.title=4 Ziffer Display
gate.memory128.title=Speicher 16 Bytes
gate.memory128.description=Static RAM: 16 x 8 bit Register
gate.pgmcnt4.title=Programmz\u00E4hler 4bit
gate.pgmcnt4.description=4 bit Programmz\u00E4hler
gate.register4.title=Register 4bit
gate.register4.description=4 bit Register
gate.register8.title=Register 8bit
gate.register8.description=8 bit register
gate.modin.title=Moduleing\u00E4nge
gate.modin.description=Eingangsgatter f\u00FCr Module - klicke den Labelbereich um einen Pin zu benennen
gate.modin.pincount=Anzahl Eing\u00E4nge
gate.modout.title=Modulausg\u00E4nge
gate.modout.description=Ausgangsgatter f\u00FCr Module
