# Main menu entries
menu.file=File
menu.file.new=New
menu.file.open=Open
menu.file.save=Save
menu.file.saveas=Save As
menu.file.modulecreate=Create Module
menu.file.properties=Properties
menu.file.export=Export
menu.file.print=Print
menu.file.exit=Exit
menu.module=Module
menu.settings=Settings
menu.settings.paintgrid=Draw Grid
menu.settings.autowire=Autowiring
menu.settings.gatedesign=Gate Design
menu.settings.gatedesign.iec=IEC
menu.settings.gatedesign.ansi=ANSI
menu.settings.mode=Mode
menu.settings.normal=Normal
menu.settings.expert=Expert
menu.settings.colormode=Colormode
menu.settings.colormode.on=On
menu.settings.colormode.off=Off
menu.settings.language=Language
menu.help=Help
menu.help.help=Help
menu.help.about=About LogicSim

# Popup menu on right-click
popup.removegate=Delete Gate
popup.properties=Properties
popup.rotate=Rotate
popup.addinput=Add Input
popup.removeinput=Remove Input

# Other main window entries
mainpanel.combo.inputs=Inputs

# Tooltips shown when hovering over toolbar buttons
toolbar.new=New
toolbar.open=Open
toolbar.save=Save
toolbar.simulate=Simulate
toolbar.inputnormal=Normal Input
toolbar.inputinv=Inverted Input
toolbar.inputhigh=High Input
toolbar.inputlow=Low Input
toolbar.wirenew=New Wire
toolbar.addpoint=Add Point to Wire
toolbar.removepoint=Remove point from wire
toolbar.zoomin=Zoom In
toolbar.zoomout=Zoom Out

# Status bar messages
status.inputnormal.help=click on input to reset to normal mode
status.inputinv.help=click on input to set inverter
status.inputhigh.help=click on input to set it to high level
status.inputlow.help=click on input to set it to low level
status.addpoint.help=click on wire to add point
status.removepoint.help=click on wire point to remove it
status.wirenew.help=Click onto Pin, Wire, Wirepoint or a blank space to insert a new wire
status.saved=Circuit saved to %s
status.aborted=aborted
status.simulation.started=simulation started
status.simulation.stopped=simulation stopped
status.pin=Pin
status.wire=wire
status.wirepoint=Point
status.wireedit=edit wire: ESC to delete last wirepoint, DEL to delete wire, click onto pin to connect
status.partsdeleted=%s parts deleted
status.partsselected=%s parts selected
status.module=Module

# Categories in component list
category.basic=Basic Gates
category.inputs=Input
category.outputs=Output
category.cpu=CPU
category.flipflops=Flipflops
category.modules=Modules

# Texts shown in dialogs
dialog.fileinfo.label=Label
dialog.fileinfo.name=Name
dialog.fileinfo.description=Description
dialog.properties.text=Text
filename.unnamed=Unnamed
dialog.savecircuit.title=Save Circuit file

# Questions, confirmations and errors
question.confirmdiscard=The circuit has been modified.\nDo you really want to discard the changes?
question.confirmsave=Save before exit?
question.confirmdelete=Do you really want to delete %s?
info.needtorestart=LogicSim needs to be restarted.
error.alreadymodule=The circuit is already a module. Abort!
error.modulenotfound=Could not find Module\n%s\nplease copy the correct Module to the modules directory
error.nomodule=circuit is not a module
error.readerror=error reading file (wrong LogicSim-version?)
error.saveerror=Error saving file

# Buttons
button.ok=OK
button.cancel=Cancel
button.yes=Yes
button.no=No
button.dontsave=Don't Save
