# Main menu entries
menu.file=File
menu.file.new=New
menu.file.open=Open
menu.file.save=Save
menu.file.saveas=Save as
menu.file.properties=Properties
menu.file.export=Export
menu.file.exit=Exit
menu.module=Module
menu.module.create=Create module
menu.module.load=Load module
menu.settings=Settings
menu.settings.paintgrid=Draw grid
menu.settings.autowire=Autowiring
menu.settings.gatedesign=Gate style
menu.settings.gatedesign.iec=IEC
menu.settings.gatedesign.ansi=ANSI
menu.settings.complexity=Complexity
menu.settings.complexity.level0=Beginner
menu.settings.complexity.level1=Level 2
menu.settings.complexity.level2=Normal
menu.settings.complexity.level3=Level 4
menu.settings.complexity.level4=Advanced
menu.settings.colormode=Colormode
menu.settings.colormode.on=On
menu.settings.colormode.off=Off
menu.settings.language=Language
menu.help=Help
menu.help.help=Help
menu.help.about=About LogicSim

# Popup menu on right-click
popup.removegate=Delete gate
popup.properties=Properties
popup.disconnect=Disconnect gate
popup.rotate=Rotate
popup.addinput=Add input
popup.removeinput=Remove input

# Other main window entries
mainpanel.combo.inputs=Inputs

# Tooltips shown when hovering over toolbar buttons
toolbar.new=New
toolbar.open=Open
toolbar.save=Save
toolbar.simulate=Simulate
toolbar.inputnormal=Normal Input
toolbar.inputinv=Inverted Input
toolbar.inputhigh=High Input
toolbar.inputlow=Low Input
toolbar.wirenew=New wire
toolbar.addpoint=Add point to wire
toolbar.removepoint=Remove point from wire
toolbar.zoomin=Zoom in
toolbar.zoomout=Zoom out

# Status bar messages
status.inputnormal.help=click on input to reset to normal mode
status.inputinv.help=click on input to set inverter
status.inputhigh.help=click on input to set it to high level
status.inputlow.help=click on input to set it to low level
status.addpoint.help=click on wire to add point
status.removepoint.help=click on wire point to remove it
status.wirenew.help=Click onto Pin, Wire, Wirepoint or a blank space to insert a new wire
status.gateadded=Gate added
status.saved=Circuit saved to %s
status.aborted=aborted
status.simulation.started=Simulation started
status.simulation.stopped=Simulation stopped
status.pin=Pin
status.wire=wire
status.wirepoint=Point
status.wireedit=edit wire: ESC to delete last wirepoint, DEL to delete wire, click onto pin to connect
status.partsdeleted=%s parts deleted
status.partsselected=%s parts selected
status.module=Module

# Categories in component list
category.basic=Basic Gates
category.inputs=Input
category.outputs=Output
category.cpu=CPU
category.flipflops=Flipflops
category.modules=Modules

# Texts shown in dialogs
dialog.fileinfo.label=Label
dialog.fileinfo.name=Name
dialog.fileinfo.description=Description
dialog.properties.text=Text
filename.unnamed=Unnamed
dialog.savecircuit.title=Save Circuit file
dialog.gateproperties.title=Gate properties

# Questions, confirmations and errors
question.confirmdiscard=The circuit has been modified.\nDo you really want to discard the changes?
question.confirmsave=Save before exit?
question.confirmdelete=Do you really want to delete %s?
info.needtorestart=LogicSim needs to be restarted.
error.alreadymodule=The circuit is already a module. Abort!
error.modulenotfound=Could not find Module\n%s\nplease copy the correct Module to the modules directory
error.nomodule=circuit is not a module
error.readerror=error reading file (wrong LogicSim-version?)
error.saveerror=Error saving file

# Buttons
button.ok=OK
button.cancel=Cancel
button.yes=Yes
button.no=No
button.dontsave=Don't Save

# Gates
gate.and.title=AND
gate.and.description=AND Gate (variable Inputcount)
gate.buffer.title=Buffer
gate.buffer.description=Buffer Gate
gate.not.title=NOT
gate.not.description=NOT Gate (Inverter)
gate.equ.title=EQUIV (XNOR)
gate.equ.description=Equivalence Gate
gate.nand.title=NAND
gate.nand.description=NAND Gate (variable Inputcount)
gate.nor.title=NOR
gate.nor.description=NOR Gate (variable Inputcount)
gate.or.title=OR
gate.or.description=OR Gate
gate.xor.title=XOR
gate.xor.description=XOR Gate
gate.binin.title=Binary Input
gate.binin.description=Binary Input (input hex or binary)
gate.binin.dec=Decimal (00..255)
gate.binin.hex=Hexadecimal (00..FF)
gate.binin.type=Type
gate.clock.title=Clock
gate.clock.description=Clock with configurable low and high time - press SPACE to start the Clock
gate.clock.enterhigh=Time High-Level (ms)
gate.clock.enterlow=Time Low-Level (ms)
gate.ondelay.title=On Delay
gate.ondelay.description=Delays the signal when turning to HIGH
gate.ondelay.delay=Time of delay (ms)
gate.offdelay.title=Off Delay
gate.offdelay.description=Delays the signal when turning to LOW
gate.offdelay.delay=Time of delay (ms)
gate.switch.title=Switch
gate.switch.description=Toggle or Momentary Switch
gate.switch.type=Type
gate.switch.momentary=Momentary switch
gate.switch.toggle=Toggle switch
gate.switch4.title=DIP-Switch (4-fold)
gate.switch4.description=4 Toggle Switches in one package
gate.switch8.title=Switch (8-fold)
gate.switch8.description=8 Toggle Switches in one package
gate.bindisp.title=Binary Display
gate.bindisp.description=Binary Display (output in hex or binary)
gate.bindisp.dec=Decimal (00..255)
gate.bindisp.hex=Hexadecimal (00..FF)
gate.bindisp.type=Type
gate.counter.title=Counter
gate.counter.description=Counter counts positive edges
gate.counter.displaytype=Type
gate.counter.dec=Decimal (00..255)
gate.counter.hex=Hexadecimal (00..FF)
gate.led.title=LED
gate.led.description=LED
gate.led8.title=Octa LED
gate.led8.description=Eight LEDs in one package
gate.sevenseg.title=7-Segment-display
gate.sevenseg.description=Display with 7 segments to output numbers from 0-9 and from a-f
gate.sevendrv.title=7-Segment-driver
gate.sevendrv.description=Binary to 7-Segment-display driver
gate.label.title=Textfield
gate.label.description=Textfield just for displaying text on the drawing surface - for documentation purposes
gate.label.text=Text
gate.triout.title=Tri-State Output
gate.triout.description=Tri-State Output
gate.dff.title=D Flip-flop
gate.dff.description=D Flip-flop
gate.drff.title=DR Flip-flop
gate.drff.description=D Flip-flop with reset
gate.dsrff.title=DSR Flip-flop
gate.dsrff.description=D Flip-flop with set and reset
gate.jkff.title=JK Flip-flop
gate.jkff.description=Positive edge triggered JK Flip-flop
gate.monoflop.title=Monoflop
gate.monoflop.description=Monoflop
gate.monoflop.hightime=Time High-Level (ms)
gate.srff.title=SR Flip-flop
gate.srff.description=SR Flip-flop
gate.srrff.title=SRR Flip-flop
gate.srrff.description=SRR Flip-flop
gate.srl.title=SR Latch
gate.srl.description=SR Latch
gate.alu8.title=ALU 8bit
gate.alu8.description=8 bit Algorithmic Logic Unit
gate.ctrllogic.title=Control Logic
gate.ctrllogic.description=Control Logic
gate.disp4d.title=4 digit Display
gate.disp4d.description=4 digit decimal Display
gate.memory128.title=Memory 16Byte
gate.memory128.description=Static RAM: 16 x 8 bit registers
gate.memory128.program=Program (instructions divided by SPACE) - 0 NOP, 1 LDA, 2 ADD, 3 SUB, 4 STA, 5 LDI, 6 JMP, 7 JC, 8 JZ, 14 OUT, 15 HLT
gate.pgmcnt4.title=ProgramCounter 4bit
gate.pgmcnt4.description=4 bit Program Counter
gate.register4.title=Register 4bit
gate.register4.description=4 bit register
gate.register8.title=Register 8bit
gate.register8.description=8 bit register
gate.modin.title=Module inputs
gate.modin.description=Input Gate for Modules - click label area to set an input pin's label
gate.modin.pincount=Number of Input Pins
gate.modout.title=Module outputs
gate.modout.description=Output Gate for Modules
