# Main menu entries
menu.file=Fichero
menu.file.new=Nuevo
menu.file.open=Abrir
menu.file.save=Guardar
menu.file.saveas=Guardar como
menu.file.properties=Propiedades
menu.file.export=Exportar
menu.file.exit=Salir
menu.module=Modulo
menu.module.create=Crear Modulo
menu.settings=Preferencias
menu.settings.paintgrid=Visibilidad Rejilla activar/desactivar
menu.settings.gatedesign=Tipo de s\u00EDmbolo en puertas
menu.settings.gatedesign.iec=IEC
menu.settings.gatedesign.ansi=ANSI
menu.settings.colormode=Modo de color
menu.settings.language=Lenguaje
menu.help=Ayuda
menu.help.help=Ayuda
menu.help.about=Acerca de LogicSim

# Popup menu on right-click
popup.removegate=Borrar Componente
popup.properties=Propiedades
popup.rotate=Girar
popup.addinput=A\u00F1adir Entrada
popup.removeinput=Quitar Entrada

# Other main window entries
mainpanel.combo.inputs=Entradas

# Tooltips shown when hovering over toolbar buttons
toolbar.new=Nuevo
toolbar.open=Abrir
toolbar.save=Guardar
toolbar.simulate=Simular
toolbar.inputnormal=Entrada normal
toolbar.inputinv=Entrada invertida
toolbar.inputhigh=Entrada a 1
toolbar.inputlow=Entrada a 0
toolbar.addpoint=A\u00F1ade punto de conexi\u00F3n
toolbar.removepoint=Eliminar punto de conexi\u00F3n

# Status bar messages
status.inputnormal.help=pulsa en la entrada para eliminar sus ajustes
status.inputinv.help=pulsa en la entrada para invertirla
status.inputhigh.help=pulsa en la entrada para colocarla a nivel alto
status.inputlow.help=pulsa en la entrada para colocarla a nivel bajo
status.addpoint.help=pulsa en el cable para colocar conexi\u00F3n
status.removepoint.help=pulsa en la conexi\u00F3n para eliminarla
status.saved=Circuito guardado como %s
status.aborted=abortado
status.module=Modulo

# Texts shown in dialogs
dialog.fileinfo.label=Etiqueta
dialog.fileinfo.name=Nombre
dialog.fileinfo.description=Comentario
dialog.properties.text=Texto
dialog.savecircuit.title=Guardar circuito en un fichero

# Questions, confirmations and errors
question.confirmdiscard=El circuito se ha modificado.\nRealmente desea descartar los cambios?
info.needtorestart=Necesita reiniciar LogicSim.
error.modulenotfound=No puedo encontrar el m\u00F3dulo\n%s\npor favor copia el m\u00F3dulo correcto en el directorio de m\u00F3dulos
error.nomodule=El circuito no es un m\u00F3dulo
error.readerror=Error leyendo el fichero (\u00BFcreado con otra versi\u00F3n de LogicSim?)
error.saveerror=Error guardando el fichero

# Buttons
button.ok=Vale
button.cancel=Cancelar
button.yes=S\u00ED
button.no=No
button.dontsave=No guardar

# Gates
gate.and.title=AND
gate.and.description=AND (Y)
gate.buffer.title=Buffer
gate.not.title=NOT (Inversor)
gate.equ.title=XNOR (=)
gate.nand.title=NAND (NO-Y)
gate.nor.title=NOR (NO-O)
gate.or.title=OR (O)
gate.xor.title=XOR (O exclusiva)
gate.binin.title=Entrada binaria
gate.binin.type=Tipo de Visualizador
gate.clock.title=Reloj
gate.ondelay.title=Retardo de 0 a 1
gate.ondelay.delay=Introduce tiempo de retardo (ms)
gate.offdelay.title=Retardo de 1 a 0
gate.offdelay.delay=Introduce tiempo de retardo (ms)
gate.switch.title=Pulsador
gate.switch.type=Tipo de pulsador
gate.switch.momentary=Moment\u00E1neo
gate.switch.toggle=Con enclavamiento
gate.sevenseg.title=Display 7 seg.
gate.label.title=Etiqueta de texto
gate.dff.title=FlipFlop D
gate.drff.title=FlipFlop DR
gate.dsrff.title=FlipFlop DSR
gate.jkff.title=FlipFlop JK
gate.monoflop.title=Monoestable
gate.monoflop.description=Monoestable
gate.srff.title=FlipFlop RS
gate.srff.description=FlipFlop RS
gate.srrff.title=FlipFlop RRS
gate.srrff.description=FlipFlop RRS
