# Main menu entries
menu.file=Fichier
menu.file.new=Nouveau
menu.file.open=Ouvrir
menu.file.save=Enregistrer
menu.file.saveas=Enregistrer sous
menu.file.modulecreate=Cr\u00E9er un module
menu.file.properties=Caract\u00E9ristiques
menu.file.export=Exporter
menu.file.print=Imprimer
menu.file.exit=Quitter
menu.settings=R\u00E9glage
menu.settings.paintgrid=Dessiner la grille
menu.settings.gatedesign=Repr\u00E9sentation
menu.settings.gatedesign.iec=IEC
menu.settings.gatedesign.ansi=ANSI
menu.settings.language=Langue
menu.help=Aide
menu.help.help=Aide
menu.help.about=\u00C0 propos de LogicSim

# Popup menu on right-click
popup.removegate=Effacer le composant
popup.properties=Caract\u00E9ristiques
popup.addinput=Ajouter une entr\u00E9e
popup.removeinput=Supprimer une entr\u00E9e

# Other main window entries
mainpanel.combo.inputs=Entr\u00E9e

# Tooltips shown when hovering over toolbar buttons
toolbar.new=Nouveau
toolbar.open=Ouvrir
toolbar.save=Enregistrer
toolbar.simulate=Simuler
toolbar.inputnormal=Entr\u00E9e normale
toolbar.inputinv=Entr\u00E9e invers\u00E9e
toolbar.inputhigh=Entr\u00E9e au niveau haut
toolbar.inputlow=Entr\u00E9e au niveau bas
toolbar.addpoint=Ajouter un point de connexion
toolbar.removepoint=Supprimer un point de connexion

# Status bar messages
status.inputnorm.help=S\u00E9lectionnez l'entr\u00E9e pour effacer la configuration actuelle
status.inputinv.help=S\u00E9lectionnez l'entr\u00E9e pour l'inverser
status.inputhigh.help=S\u00E9lectionnez l'entr\u00E9e pour la mettre au niveau haut
status.inputlow.help=S\u00E9lectionnez l'entr\u00E9e pour la mettre au niveau bas
status.addpoint.help=S\u00E9lectionnez un fil pour rajouter un point
status.removepoint=S\u00E9lectionnez un point de connexion pour le supprimer
status.saved=Le sch\u00E9ma %s a \u00E9t\u00E9 enregistr\u00E9
status.aborted=Abandonn\u00E9
status.module=Module

# Texts shown in dialogs
dialog.fileinfo.label=Étiquette
dialog.fileinfo.name=Nom
dialog.fileinfo.description=Description

# Questions, confirmations and errors
question.confirmdiscard=Le circuit a \u00E9t\u00E9 modifi\u00E9.\nVoulez vous vraiment perdre ce circuit?
info.needtorestart=LogicSim doit \u00EAtre red\u00E9marr\u00E9.
error.modulenotfound=Le module \n%s n'a pas \u00E9t\u00E9 trouv\u00E9.\nCopiez le module dans le r\u00E9pertoire appropri\u00E9.
error.nomodule=Ce sch\u00E9ma n'est pas un module
error.readerror=Erreur de lecture
error.saveerror=Erreur pendant la sauvegarde

# Buttons
button.cancel=Annuler
button.yes=Oui
button.no=Non

# Gates
gate.and.title=AND
gate.and.description=Et (AND)
gate.buffer.title=Buffer
gate.not.title=Non (NOT)
gate.equ.title=<-> (NXOR)
gate.nand.title=Non Et (NAND)
gate.nor.title=Non Ou (NOR)
gate.or.title=Ou (OR)
gate.xor.title=Ou exclusif (XOR)
gate.binin.title=roue codeuse
gate.binin.type=Type d'affichage
gate.binin.dec=D\u00E9cimal (00..99)
gate.binin.hex=Hexad\u00E9cimal (00..FF)
gate.clock.title=Horloge
gate.clock.enterhigh=Dur\u00E9e du palier haut (ms)
gate.clock.enterlow=Dur\u00E9e du palier bas (ms)
gate.ondelay.title=Temporisation travail
gate.ondelay.delay=D\u00E9calage (ms)
gate.offdelay.title=Temporisation repos
gate.offdelay.delay=D\u00E9calage (ms)
gate.switch.title=Bouton
gate.switch.type=Type de bouton
gate.switch.momentary=Bouton poussoir
gate.switch.toggle=Interrupteur
