# Main menu entries
menu.file=File
menu.file.new=Nuovo
menu.file.open=Apri
menu.file.save=Salva
menu.file.saveas=Salva con nome
menu.file.modulecreate=Crea Modulo
menu.file.properties=Propriet\u00e0
menu.file.export=Export
menu.file.print=Stampa
menu.file.exit=Esci
menu.module=Modulo
MENU_MODULEPROPERTIES=Propriet\u00e0 modulo
menu.settings=Impostazioni
menu.settings.paintgrid=Visualizza Griglia
menu.settings.gatedesign=Impostazioni Porte
menu.settings.gatedesign.iec=Simboli IEC
menu.settings.gatedesign.ansi=Simboli ANSI
menu.settings.language=Lingua
menu.help=Aiuto
menu.help.help=Aiuto

# Popup menu on right-click
popup.removegate=Elimina
popup.properties=Propriet\u00e0

# Other main window entries
mainpanel.combo.inputs=Ingressi

# Tooltips shown when hovering over toolbar buttons
toolbar.new=Nuovo
toolbar.open=Apri
toolbar.save=Salva
toolbar.simulate=Avvia Simulazione
toolbar.addpoint=Aggiungi giunzione
toolbar.removepoint=Rimuovi giunzione

# Status bar messages
status.inputnormal.help=Click sull'ingresso per rimuovere le impostazioni
status.inputinv.help=Click sull'ingresso per impostare la negazione
status.inputhigh.help=Click sull'ingresso per impostarlo a livello ALTO
status.inputlow.help=Click sull'ingresso per impostarlo a livello BASSO
status.addpoint.help=Click sul filo per aggiungere una giunzione
status.removepoint.help=Click sulla giunzione per rimuoverla
status.saved=Il circuito %s \u00e8 stato salvato
status.aborted=Annullato
status.module=Modulo

# Texts shown in dialogs
dialog.fileinfo.label=Etichetta Modulo
dialog.fileinfo.name=Nome Modulo
dialog.fileinfo.description=Descrizione
dialog.savecircuit.title=Salva il Circuito
dialog.gateproperties.title=Propriet\u00e0

# Questions, confirmations and errors
question.confirmdelete=Confermi eliminazione\n%s ?
info.needtorestart=LogicSim deve essere riavviato.
MESSAGE_ENTER_LABEL=Inserisci Etichetta
MESSAGE_ENTER_TIME_HIGH=Inserisci tempo per livello ALTO (ms)
MESSAGE_ENTER_TIME_LOW=Inserisci il tempo per livello BASSO (ms)
error.modulenotfound=Impossibile trovare il Modulo\n%s\ncopiare il modulo corretto nella cartella moduli
error.nomodule=Il circuito non \u00e8 un modulo
error.readerror=Errore di lettura file (errata versione di LogicSim?)
error.saveerror=Errore di scrittura file

# Buttons
button.ok=OK
button.cancel=Annulla

# Gates
gate.switch.title=Switch
gate.switch.type=Tipo di switch
gate.switch.toggle=Interruttore
gate.switch.momentary=Pulsante
gate.led.title=LED
gate.and.title=AND
gate.buffer.title=Buffer
gate.nand.title=NAND
gate.or.title=OR
gate.nor.title=NOR
gate.not.title=NOT (Inverter)
gate.xor.title=XOR
gate.equ.title=EXNOR (Comp. Dig.)
toolbar.input.normal=Ingresso NORMALE
toolbar.input.inv=Ingresso NEGATO
toolbar.input.high=Ingresso ALTO
toolbar.input.low=Ingresso BASSO
GATE_RSFF=RS FlipFlop
gate.dff.title=D FlipFlop
gate.drff.title=D FlipFlop & Reset
gate.jkff.title=JK FF (Edge Trigg)
GATE_JKMSFF=JKMS FlipFlop
GATE_TFF=T FlipFlop
gate.clock.title=Clock
gate.monoflop.title=Monostabile
gate.ondelay.title=Ritardo OFF-ON
gate.offdelay.title=Ritardo ON-OFF
gate.binin.title=Contraves Binario
gate.label.title=Etichetta di Testo

gate.binin.type=Tipo di Display
gate.binin.hex=Hex (00..FF)
gate.binin.dec=Dec (00..99)

gate.ondelay.delay=Inserisci Tempo di Ritardo (ms)
gate.offdelay.delay=Inserisci Tempo di Ritardo (ms)
