# Main menu entries
menu.file=Bestand
menu.file.new=Nieuw
menu.file.open=Open
menu.file.save=Opslaan
menu.file.saveas=Opslaan Als
menu.file.modulecreate=Maak Module
menu.file.properties=Eigenschappen
menu.file.export=Exporteer
menu.file.print=Afdrukken
menu.file.exit=Afsluiten
menu.module=Module
menu.settings=Voorkeuren
menu.settings.paintgrid=toon raster
menu.settings.gatedesign=poortsymbolen
menu.settings.gatedesign.iec=IEC
menu.settings.gatedesign.ansi=ANSI
menu.settings.language=Taal
menu.help=Help
menu.help.help=Help
menu.help.about=Over LogicSim

# Popup menu on right-click
popup.removegate=Verwijder Poort
popup.properties=Eigenschappen

# Other main window entries
mainpanel.combo.inputs=Inputs

# Tooltips shown when hovering over toolbar buttons
toolbar.new=Nieuw
toolbar.open=Open
toolbar.save=Opslaan
toolbar.simulate=Simuleer
toolbar.addpoint=Voeg punt aan draad toe
toolbar.removepoint=Verwijder punt van draad

# Status bar messages
status.inputnormal.help=klik op input om input instelling te verwijderen
status.inputinv.help=klik op input om inverter in te stellen
status.inputhigh.help=klik op input om hoog niveau in te stellen
status.inputlow.help=klik op input om laag niveau in te stellen
status.addpoint.help=klik op de draad om een punt toe te voegen
status.removepoint.help=klik op de draad om hem te verwijderen
status.saved=Schakeling bewaard als %s
status.aborted=afgebroken
status.module=Module

# Texts shown in dialogs
dialog.fileinfo.label=module label
dialog.fileinfo.name=module naam
dialog.fileinfo.description=omschrijving
dialog.savecircuit.title=Opslaan Circuit bestand

# Questions, confirmations and errors
question.confirmdelete=Wil je\n%s werkelijk verwijderen ?
info.needtorestart=LogicSim moet opnieuw gestart worden.
MESSAGE_ENTER_TIME_HIGH=Geef de tijd voor hoog signaal (ms)
MESSAGE_ENTER_TIME_LOW=Geef de de tijd voor laag signaal (ms)
MESSAGE_ENTER_LABEL=Geef Label
question.confirmdiscard=De schakeling is gewijzigd.\nWil je de schakeling werkelijk niet bewaren?
error.modulenotfound=Kan Module\n%s niet vinden\nKopieer a.u.b. de juiste Module naar de modulenmap
error.nomodule=schakeling is geen module
error.readerror=fout tijdens lezen bestand (verkeerde LogicSim-versie?)
error.saveerror=Fout tijdens opslaan bestand

# Buttons
button.ok=Gebruik dit
button.cancel=Annuleer

# Gates
gate.switch.title=Schakelaar
gate.switch.type=Schakelaar-Type
gate.switch.toggle=Omschakelknop
gate.switch.momentary=Drukknop
gate.led.title=LED
gate.and.title=EN
gate.buffer.title=Buffer
gate.nand.title=NEN
gate.or.title=OF
gate.nor.title=NOF
gate.not.title=NIET (Inverter)
gate.xor.title=XOF (ongelijk)
gate.equ.title=<-> (gelijk)
toolbar.input.normal=Normaal Input
toolbar.input.inv=Input Inverter
toolbar.input.high=Input Hoog
toolbar.input.low=Input Laag
GATE_RSFF=RS FlipFlop
gate.dff.title=D FlipFlop
gate.drff.title=D FlipFlop & Reset
gate.jkff.title=JK FF (edge triggered)
GATE_JKMSFF=JKMS FlipFlop
GATE_TFF=T FlipFlop
gate.clock.title=Klok
gate.monoflop.title=Monoflop
gate.ondelay.title=Vertraging aan
gate.offdelay.title=vertraging uit
gate.binin.title=binaire input
GATE_LCD=LCD
gate.sevenseg.title=7-segments display
gate.label.title=Text Label

gate.binin.type=Display Type
GATE_BINARYINPUT_PROPERTIES=Binaire Input Eigenschappen
gate.binin.hex=Hexadecimaal (00..FF)
gate.binin.dec=Decimaal (00..99)

GATE_LCD_PROPERTIES=LCD Eigenschappen
GATE_MONOFLOP_PROPERTIES=MonoFlop Eigenschappen

gate.ondelay.delay=Voer Vertraging in (ms)
gate.offdelay.delay=Voer vertraging in (ms)
