# Main menu entries
menu.file=Arkiv
menu.file.new=Nytt
menu.file.open=\u00d6ppna
menu.file.save=Spara
menu.file.saveas=Spara som
menu.file.modulecreate=Bygg modul
menu.file.properties=Egenskaper
menu.file.export=Exportera
menu.file.print=Skriv ut
menu.file.exit=Avsluta
menu.module=Modul
menu.settings=Inst\u00e4llningar
menu.settings.paintgrid=Visa grid
menu.settings.gatedesign=Grindstandard
menu.settings.gatedesign.iec=IEC
menu.settings.gatedesign.ansi=ANSI
menu.settings.language=Spr\u00e5k
menu.help=Hj\u00e4lp
menu.help.help=Hj\u00e4lp
menu.help.about=Om LogicSim

# Popup menu on right-click
popup.removegate=Ta bort grind
popup.properties=Egenskaper

# Other main window entries
mainpanel.combo.inputs=Ing\u00e5ngar

# Tooltips shown when hovering over toolbar buttons
toolbar.new=Nytt
toolbar.open=\u00d6ppna
toolbar.save=Spara
toolbar.simulate=Simulera
toolbar.addpoint=L\u00e4gga till en punkt till en ledning
toolbar.removepoint=Ta bort punkt fr\u00e5n ledningen

# Status bar messages
status.inputnormal.help=Klicka p\u00e5 ing\u00e5ngen f\u00d6r att ta bort nuvarande inst\u00e4llningar
status.inputinv.help=Klicka p\u00e5 ing\u00e5ngen f\u00d6r att aktivera inverteringen
status.inputhigh.help=Klicka p\u00e5 ing\u00e5ngen f\u00d6r att s\u00e4tta den till h\u00d6gniv\u00e5
status.inputlow.help=Klicka p\u00e5 ing\u00e5ngen f\u00d6r att s\u00e4tta den till l\u00e5gniv\u00e5
status.addpoint.help=Klicka p\u00e5 en ledning f\u00d6r att l\u00e4gga till en punkt
status.removepoint.help=Klicka p\u00e5 en punkt i en ledning f\u00d6r att ta bort punkten
status.saved=Kretsen %s sparad
status.aborted=Avbruten
status.module=Modul

# Texts shown in dialogs
dialog.fileinfo.label=Moduletikett
dialog.fileinfo.name=Modulnamn
dialog.fileinfo.description=Beskrivning
dialog.savecircuit.title=Spara kretsen

# Questions, confirmations and errors
question.confirmdiscard=Kretsen har modifierats.\nVill du verkligen inte spara dina \u00e4ndringar?
question.confirmdelete=Vill du verkligen ta bort filen %s ?
info.needtorestart=LogicSim m\u00e5ste startas om.
MESSAGE_ENTER_TIME_HIGH=Tidsl\u00e4ngd H\u00d6gniv\u00e5 (ms)
MESSAGE_ENTER_TIME_LOW=Tidsl\u00e4ngd L\u00e5gniv\u00e5 (ms)
MESSAGE_ENTER_LABEL=Skriv texten
error.modulenotfound=Modulen %s\nkunde inte hittas.\nKopiera modulfilen till katalogen modules.
error.nomodule=Kretsen \u00e4r ingen modul
error.readerror=Filen kunde inte l\u00e4sas (fel version av LogicSim?)
error.saveerror=Filen kunde inte sparas

# Buttons
button.ok=Anv\u00e4nd
button.cancel=Avbryt

# Gates
gate.switch.title=Brytare
gate.switch.type=Brytartyp
gate.switch.toggle=Omkopplare
gate.switch.momentary=Tryckknapp
gate.led.title=LED
gate.and.title=AND (och)
gate.buffer.title=Buffer
gate.nand.title=NAND
gate.or.title=OR (eller)
gate.nor.title=NOR
gate.not.title=NOT (icke)
gate.xor.title=XOR (antingen eller)
gate.equ.title=<-> (ekvivalens)
GATE_NORMALINPUT=Normal ing\u00e5ng
GATE_INPUT_INVERTER=Inverterad ing\u00e5ng
GATE_INPUT_HIGH=H\u00d6ging\u00e5ng
GATE_INPUT_LOW=L\u00e5ging\u00e5ng
GATE_RSFF=RS-vippa
GATE_DFF=D-vippa
GATE_DRFF=D FlipFlop & Reset
GATE_JKFF=JK-vippa (flankstyrd)
GATE_JKMSFF=JK-MS-vippa
GATE_TFF=T-vippa
gate.clock.title=Klocka
GATE_MONOFLOP=Monoflop
gate.ondelay.title=P\u00e5slagsf\u00d6rdr\u00d6jning
gate.offdelay.title=Avslagsf\u00d6rdr\u00d6jning
gate.binin.title=Bin\u00e4rinmatning
GATE_LCD=LCD
gate.label.title=Textf\u00e4lt

gate.binin.type=Displaytyp
GATE_BINARYINPUT_PROPERTIES=Bin\u00e4rinmatningens egenskaper
gate.binin.hex=Hexadecimal (00..FF)
gate.binin.dec=Decimal (00..99)

GATE_LCD_PROPERTIES=LCD-egenskaper

GATE_MONOFLOP_PROPERTIES=MonoFlop-egenskaper

gate.ondelay.delay=F\u00d6rdr\u00d6jningstid (ms)
gate.offdelay.delay=F\u00d6rdr\u00d6jningstid (ms)
