# Main menu entries
menu.file=Dosya
menu.file.new=Yeni
menu.file.open=A\u00e7
menu.file.save=Kaydet
menu.file.saveas=Farkl\u0131 Kaydet
menu.file.modulecreate=Mod\u00fcl Olu\u015ftur
menu.file.properties=Mod\u00fcl \u00D6zellikleri
menu.file.export=\u00e7\u0131kart
menu.file.print=Yazd\u0131r
menu.file.exit=\u00e7\u0131k\u0131\u015f
menu.module=Mod\u00fcl
menu.settings=Ayarlar
menu.settings.paintgrid=Izgara \u00e7iz
menu.settings.gatedesign=Kap\u0131 stili
menu.settings.gatedesign.iec=IEC
menu.settings.gatedesign.ansi=ANSI
menu.settings.language=Dil
menu.help=Yard\u0131m
menu.help.help=Yard\u0131m
menu.help.about=LogicSim Hakk\u0131nda

# Popup menu on right-click
popup.removegate=Kap\u0131y\u0131 kald\u0131r
popup.properties=\u00D6znitelikler

# Other main window entries
mainpanel.combo.inputs=Giri\u015fler

# Tooltips shown when hovering over toolbar buttons
toolbar.new=Yeni
toolbar.open=A\u00e7
toolbar.save=Kaydet
toolbar.simulate=\u00e7al\u0131\u015ft\u0131r
toolbar.addpoint=Hat \u00fczerine nokta ekle
toolbar.removepoint=Noktay\u0131 hat \u00fczerinden kald\u0131r

# Status bar messages
status.inputnormal.help=giri\u015f ayar\u0131n\u0131 kald\u0131rmak i\u00e7in giri\u015fi t\u0131klay\u0131n
status.inputinv.help=Invertor'\u00fc ayarlamak i\u00e7in giri\u015fi t\u0131klay\u0131n
status.inputhigh.help=high level giri\u015fe ayarlamak i\u00e7in giri\u015fi t\u0131klay\u0131n
status.inputlow.help=low level giri\u015fe ayarlamak i\u00e7in giri\u015fi t\u0131klay\u0131n
status.addpoint.help=hatta nokta eklemek i\u00e7in t\u0131klay\u0131n
status.removepoint.help=hat \u00fczerinden noktay\u0131 kald\u0131rmak i\u00e7in t\u0131klay\u0131n
status.saved=Devre kaydedildi : %s
status.aborted=Ba\u011flant\u0131 koptu.
status.module=Mod\u00fcl

# Texts shown in dialogs
dialog.fileinfo.label=modul label
dialog.fileinfo.name=modul ismi
dialog.fileinfo.description=modul tanimi
dialog.savecircuit.title=Devreyi dosya olarak kaydet

# Questions, confirmations and errors
question.confirmdiscard=Devrede de\u011fi\u015fiklikler yap\u0131ld\u0131.\nKaydetmeden \u00e7\u0131kmak istiyor musunuz??
question.confirmdelete=Ger\u00e7ekten silmek istiyor musunuz\n%s ?
MESSAGE_ENTER_TIME_HIGH=HIGH level pulse s\u00fcresini giriniz.(ms)
MESSAGE_ENTER_TIME_LOW=LOW level pulse s\u00fcresini giriniz.(ms)
MESSAGE_ENTER_LABEL=Label giriniz.
info.needtorestart=LogicSim yeniden ba\u015flat\u0131lmal\u0131.
error.modulenotfound=Mod\u00fcl bulunamad\u0131\n%s\nL\u00fctfen do\u011fru mod\u00fcl\u00fc mod\u00fcl klas\u00f6r\u00fcnden kopyalay\u0131n\u0131z.
error.nomodule=Bu devre bir mod\u00fcl de\u011fil.
error.readerror=Dosya okuma hatas\u0131 (wrong LogicSim-version?)
error.saveerror=Dosya kaydetme hatas\u0131.

# Buttons
button.ok=Kullan
button.cancel=\u0130ptal

# Gates
gate.switch.title=Anahtar
gate.switch.type=Anahtar tipi
gate.switch.toggle=Toggle-Buton
gate.switch.momentary=Buton
gate.led.title=LED
gate.and.title=Ve Kap\u0131s\u0131 (AND)
gate.buffer.title=Buffer
gate.nand.title=Ve-De\u011fil Kap\u0131s\u0131 (NAND)
gate.or.title=Veya Kap\u0131s\u0131 (OR)
gate.nor.title=Veya-De\u011fil Kap\u0131s\u0131 (NOR)
gate.not.title=De\u011fil kap\u0131s\u0131 (Inverter)
gate.xor.title=\u00D6zel-Veya Kap\u0131s\u0131 (XOR)
gate.equ.title=<-> (Equivalence)
toolbar.input.normal=Normal Giri\u015f
toolbar.input.inv=Ters giri\u015f
toolbar.input.high=Giri\u015f High
toolbar.input.low=Giri\u015f Low
GATE_RSFF=RS FlipFlop
gate.dff.title=D FlipFlop
gate.drff.title=D FlipFlop & Reset
gate.jkff.title=JK FF (tetiklemeli)
GATE_JKMSFF=JKMS FlipFlop
GATE_TFF=T FlipFlop
gate.clock.title=Saat (Clock)
gate.monoflop.title=Monoflop
gate.ondelay.title=Gecikmeyi a\u00e7
gate.offdelay.title=Gecikmeyi kapat
gate.binin.title=\u0130kili giri\u015f
gate.label.title=Metin ekle

gate.binin.type=Ekran tipi
GATE_BINARYINPUT_PROPERTIES=\u0130kili giri\u015f \u00f6znitelikleri
gate.binin.hex=Hexadecimal (00..FF)
gate.binin.dec=Decimal (00..99)

GATE_MONOFLOP_PROPERTIES=MonoFlop \u00D6zellikler

gate.ondelay.delay=Gecikme s\u00fcresini giriniz (ms)
gate.offdelay.delay=Gecikme s\u00fcresini giriniz (ms)
