menu.file=Datei
menu.file.new=Neu
menu.file.open=\u00D6ffnen
menu.file.save=Speichern
menu.file.saveas=Speichern Als
menu.file.modulecreate=Modul erstellen
menu.file.properties=Eigenschaften
menu.file.export=Export
menu.file.print=Drucken
menu.file.exit=Exit

menu.settings=Einstellungen
menu.settings.paintgrid=Raster zeichnen
menu.settings.autowire=Autom. Verkabelung
menu.settings.gatedesign=Gatterdesign
menu.settings.gatedesign.iec=IEC
menu.settings.gatedesign.ansi=ANSI
menu.settings.mode=Modus
menu.settings.normal=Normal
menu.settings.expert=Experte
menu.settings.colormode=Farbmodus
menu.settings.colormode.on=An
menu.settings.colormode.off=Aus
menu.settings.language=Sprache
menu.help=Hilfe
menu.help.help=Hilfe
menu.help.about=\u00DCber LogicSim

popup.removegate=Gatter l\u00F6schen
popup.properties=Eigenschaften
popup.rotate=Rotieren
popup.addinput=Eingang hinzuf\u00FCgen
popup.removeinput=Eingang entfernen

mainpanel.combo.inputs=Eing\u00E4nge

toolbar.new=Neu
toolbar.open=\u00D6ffnen
toolbar.save=Speichern
toolbar.simulate=Simulieren
toolbar.inputnorm=Normaler Eingang
toolbar.inputinv=Invertierter Eingang
toolbar.inputhigh=High Eingang
toolbar.inputlow=Low Eingang
toolbar.wirenew=Neues Kabel
toolbar.addpoint=Punkt zu Kabel hinzuf\u00FCgen
toolbar.removepoint=Punkt von Kabel entfernen
toolbar.zoomin=Hereinzoomen
toolbar.zoomout=Herauszoomen

status.inputnormal.help=Klicke auf einen Input, um ihn auf NORMAL zu setzen
status.inputinv.help=Klicke auf einen Input, um ihn zu invertieren
status.inputhigh.help=Klicke auf einen Input, um ihn auf HIGH zu setzen
status.inputlow.help=Klicke auf einen Input, um ihn auf LOW zu setzen
status.addpoint.help=Klicke auf ein Kabel um einen Punkt hinzuzuf\u00FCgen
status.removepoint.help=Klicke auf ein Kabel um einen Punkt zu entfernen
status.wirenew.help=Klicke auf ein Pin, Kabel, Punkt oder freie Stelle um ein Kabel einzufügen
status.saved=Schaltplandatei gespeichert unter %s
status.aborted=abgebrochen
status.simulation.started=Simulation gestarted
status.simulation.stopped=Simulation gestoppt
pin=Anschlusspin
wire=Kabel
wirepoint=Punkt
wireedit=Kabel bearbeiten: ESC zum L\u00F6schen des letzten Punkts, DEL zum L\u00F6schen des Kabels, Klick auf Pin zum Beenden
partsdeleted=%s Teile gel\u00F6scht
partsselected=%s Teile ausgew\u00E4hlt
category.basic=Grundgatter
category.inputs=Eingabe
category.outputs=Ausgabe
category.cpu=CPU
category.flipflops=Flip-Flops
category.modules=Module
status.module=Modul

dialog.fileinfo.label=Beschriftung
dialog.fileinfo.name=Name
dialog.fileinfo.description=Beschreibung
dialog.properties.text=Text
filename.unnamed=Unbenannt

dialog.savecircuit.title=Schaltplandatei speichern

question.confirmdiscard=Der Schaltplan wurde ver\u00E4ndert.\nM\u00F6chtest Du die \u00C4nderungen wirklich verwerfen?
question.confirmsave=Speichern vor dem Schließen?
question.confirmdelete=Wirklich %s l\u00F6schen?
info.needtorestart=LogicSim muss neu gestartet werden
error.alreadymodule=Der Schaltkreis ist bereits ein Modul. Abbruch!
error.modulenotfound=Kann das Modul %s nicht finden. Bitte kopiere die Moduldatei in das modules-Unterverzeichnis.
error.nomodule=Die Schaltplandatei ist kein Modul
error.readerror=Fehler beim Laden der Datei (falsche LogicSim-Version?)
error.saveerror=Fehler beim Speichern

button.ok=OK
button.cancel=Abbruch
button.yes=Ja
button.no=Nein
button.dontsave=Nicht Speichern
