[menu]
menu.file=Arkiv
menu.file.new=Nytt
menu.file.open=Öppna
menu.file.save=Spara
menu.file.saveas=Spara som
menu.file.modulecreate=Bygg modul
menu.file.properties=Egenskaper
menu.file.export=Exportera
menu.file.print=Skriv ut
menu.file.exit=Avsluta

menu.module=Modul

menu.settings=Inställningar
menu.settings.paintgrid=Visa grid
menu.settings.gatedesign=Grindstandard
menu.settings.gatedesign.iec=IEC
menu.settings.gatedesign.ansi=ANSI
menu.settings.language=Språk

menu.help=Hjälp
menu.help.help=Hjälp
menu.help.about=Om LogicSim

[context menu]
popup.removegate=Ta bort grind
popup.properties=Egenskaper

[toolbar]
toolbar.new=Nytt
toolbar.open=Öppna
toolbar.save=Spara
toolbar.simulate=Simulera
toolbar.addpoint=Lägga till en punkt till en ledning
toolbar.removepoint=Ta bort punkt från ledningen

[messages]
mainpanel.combo.inputs=Ingångar
question.confirmdelete=Vill du verkligen ta bort filen %s ?
info.needtorestart=LogicSim måste startas om.
dialog.savecircuit.title=Spara kretsen
MESSAGE_ENTER_TIME_HIGH=Tidslängd Högnivå (ms)
MESSAGE_ENTER_TIME_LOW=Tidslängd Lågnivå (ms)
dialog.fileinfo.name=Modulnamn
dialog.fileinfo.description=Beskrivning
dialog.fileinfo.label=Moduletikett
MESSAGE_ENTER_LABEL=Skriv texten
question.confirmdiscard=Kretsen har modifierats.\nVill du verkligen inte spara dina ändringar?

[messages in status bar]
status.inputnormal.help=Klicka på ingången för att ta bort nuvarande inställningar
status.inputinv.help=Klicka på ingången för att aktivera inverteringen
status.inputhigh.help=Klicka på ingången för att sätta den till högnivå
status.inputlow.help=Klicka på ingången för att sätta den till lågnivå
status.addpoint.help=Klicka på en ledning för att lägga till en punkt
status.removepoint.help=Klicka på en punkt i en ledning för att ta bort punkten
status.saved=Kretsen %s sparad
status.aborted=Avbruten
status.module=Modul

[error messages]
error.nomodule=Kretsen är ingen modul
error.readerror=Filen kunde inte läsas (fel version av LogicSim?)
error.saveerror=Filen kunde inte sparas
error.modulenotfound=Modulen %s\nkunde inte hittas.\nKopiera modulfilen till katalogen modules.

[BUTTONS]
button.ok=Använd
button.cancel=Avbryt

[GATES]
GATE_SWITCH=Brytare
GATE_SWITCH_TYPE=Brytartyp
GATE_SWITCH_TOGGLE=Omkopplare
GATE_SWITCH_CLICK=Tryckknapp
GATE_LED=LED
GATE_AND=AND (och)
GATE_NAND=NAND
GATE_OR=OR (eller)
GATE_NOR=NOR
GATE_NOT=NOT (icke)
GATE_XOR=XOR (antingen eller)
GATE_EQUIVALENCE=<-> (ekvivalens)
GATE_NORMALINPUT=Normal ingång
GATE_INPUT_INVERTER=Inverterad ingång
GATE_INPUT_HIGH=Högingång
GATE_INPUT_LOW=Lågingång
GATE_RSFF=RS-vippa
GATE_DFF=D-vippa
GATE_DRFF=D FlipFlop & Reset
GATE_JKFF=JK-vippa (flankstyrd)
GATE_JKMSFF=JK-MS-vippa
GATE_TFF=T-vippa
GATE_CLOCK=Klocka
GATE_MONOFLOP=Monoflop
GATE_TURNONDELAY=Påslagsfördröjning
GATE_TURNOFFDELAY=Avslagsfördröjning
GATE_BINARYINPUT=Binärinmatning
GATE_LCD=LCD
GATE_SEVENSEGMENT=7-segmentsdisplay
GATE_TEXTLABEL=Textfält

GATE_BINARYINPUT_DISPLAYTYPE=Displaytyp
GATE_BINARYINPUT_PROPERTIES=Binärinmatningens egenskaper
GATE_BINARYINPUT_HEX=Hexadecimal (00..FF)
GATE_BINARYINPUT_DEC=Decimal (00..99)

GATE_LCD_PROPERTIES=LCD-egenskaper

GATE_MONOFLOP_PROPERTIES=MonoFlop-egenskaper

GATE_TURNONDELAY_TIME=Fördröjningstid (ms)
GATE_TURNOFFDELAY_TIME=Fördröjningstid (ms)
